nodeLinker: pnp

packageExtensions:
  "@nestjs/core@*":
    dependencies:
      "@nestjs/microservices": "*"
      "@nestjs/websockets": "*"
  "@nestjs/microservices@*":
    dependencies:
      "@grpc/grpc-js": "*"
      "@grpc/proto-loader": "*"
      "kafkajs": "*"
      "mqtt": "*"
      "nats": "*"
      "ioredis": "*"
      "amqplib": "*"
      "amqp-connection-manager": "*"
  "@nestjs/websockets@*":
    dependencies:
      "@nestjs/platform-socket.io": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

supportedArchitectures:
  os:
    - darwin
    - win32
    - linux

yarnPath: .yarn/releases/yarn-3.4.1.cjs
